# Generated by Django 5.0 on 2024-09-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
