# Generated by Django 5.0 on 2024-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprs_app', '0002_coordinatorprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='coordinatorprofile',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='coordinatorprofile',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='coordinatorprofile',
            name='password',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
