# Generated by Django 5.0 on 2024-09-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprs_app', '0003_remove_coordinatorprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
