# Generated by Django 5.0 on 2024-09-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprs_app', '0004_remove_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
