# Generated by Django 5.0 on 2024-09-14 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprs_app', '0005_alter_coordinatorprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('college_email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('personal_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('degree_program', models.CharField(max_length=100)),
                ('year_of_enrollment', models.IntegerField()),
                ('year_of_graduation', models.IntegerField()),
                ('tenth_percentage', models.FloatField()),
                ('tenth_passing_year', models.IntegerField()),
                ('tenth_school', models.CharField(max_length=200)),
                ('twelfth_stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Other', 'Other')], max_length=50)),
                ('twelfth_percentage', models.FloatField()),
                ('twelfth_passing_year', models.IntegerField()),
                ('twelfth_school', models.CharField(max_length=200)),
                ('ug_course', models.CharField(blank=True, max_length=100, null=True)),
                ('ug_passing_year', models.IntegerField(blank=True, null=True)),
                ('ug_cgpa', models.FloatField(blank=True, null=True)),
                ('ug_college_university', models.CharField(blank=True, max_length=200, null=True)),
                ('other_course', models.CharField(blank=True, max_length=100, null=True)),
                ('other_passing_year', models.IntegerField(blank=True, null=True)),
                ('other_cgpa', models.FloatField(blank=True, null=True)),
                ('other_college_university', models.CharField(blank=True, max_length=200, null=True)),
                ('backlogs', models.IntegerField(default=0)),
                ('skills', models.TextField()),
                ('certifications', models.TextField()),
                ('internship_details', models.TextField()),
                ('projects', models.TextField()),
                ('achievements', models.TextField()),
                ('extracurricular_activities', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
                ('placement_preferences', models.TextField()),
                ('placed_status', models.BooleanField(default=False)),
                ('job_offers', models.TextField(blank=True, null=True)),
                ('date_of_last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('nationality', models.CharField(max_length=50)),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='cprs_app.studentprofile')),
            ],
        ),
    ]
