# Generated by Django 5.0 on 2024-09-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprs_app', '0006_studentinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='backlogs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='degree_program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='extracurricular_activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='internship_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='placement_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='tenth_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='tenth_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='tenth_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='twelfth_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='twelfth_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='twelfth_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='twelfth_stream',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='year_of_enrollment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='year_of_graduation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
