# Generated by Django 5.0 on 2024-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprs_app', '0009_jobdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdrive',
            name='vacancies',
            field=models.IntegerField(default=0),
        ),
    ]
