# Generated by Django 5.0 on 2024-10-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprs_app', '0011_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdrive',
            name='tentative_drive_date',
            field=models.DateField(null=True),
        ),
    ]
