# Generated by Django 5.0 on 2024-10-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprs_app', '0013_appliedjob_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
